app:
    build: app
    links:
      - redis

haproxy:
    image: tutum/haproxy
    links:
      - app
    environment:
      - BACKEND_PORT=5000

redis:
    image: redis
nginx:
    build: nginx
    ports:
      - "80:80"
    links:
      - haproxy
